### ISSUE TITLE
How create a new subscriber?

### ISSUE THREAD

**Issue by opaniagu** [fastogt/fastocloud_admin#11]
Hi, i installed all local. But I can not find how create new subscriber like as:

https://www.fastotv.com/subscriber/profile/

Thanks

**Comment by topilski** [comment]
Hey, please change this line https://github.com/fastogt/fastocloud_admin/blob/master/app/config/config.py#L6 and restart service

**Comment by opaniagu** [comment]
Excellent! Thanks
