### ISSUE TITLE
Local Installtion - Subscriber Profile

### ISSUE THREAD

**Issue by opaniagu** [fastogt/fastocloud_admin#13]
Hi, I can show subscriber botton, and I can create new subscriber after modify config.py.

But user can not login, is necessary config mail server? 

Then, how subscriber show profile to create device like:

https://fastotv.com/subscriber/profile/

Thanks

**Comment by topilski** [comment]
yes https://github.com/fastogt/fastocloud_admin/blob/master/app/config/mail_config.py on fastotv_site same file

**Comment by opaniagu** [comment]
Hi, I configure email is OK.

The problem is can not view profile to create device like:

https://fastotv.com/subscriber/profile/

!
![Screenshot_2019-09-22 Profile FastoTV](https://user-images.githubusercontent.com/18073752/65387385-46047c80-dd1d-11e9-9179-802e6e38b58a.png)

**Comment by topilski** [comment]
Very interesting, can you show screen

**Comment by opaniagu** [comment]
I follow the next step:
1) create subscriber (active) --> first image
2) try login using subscriber --> second image

The message is "User Not found"

![Screenshot_2019-09-22 Subscribers FastoCloud](https://user-images.githubusercontent.com/18073752/65388816-f7a7ab80-dd25-11e9-9fa2-6995a6ce1f27.png)
![Screenshot_2019-09-22 Login FastoCloud](https://user-images.githubusercontent.com/18073752/65388850-05f5c780-dd26-11e9-9b38-a3b388b23c23.png)

**Comment by opaniagu** [comment]
I will install fastotv_site_new. Thanks
