### ISSUE TITLE
Add relay

### ISSUE THREAD

**Issue by opaniagu** [fastogt/fastocloud_admin#14]
Hi, I try add relay. I copied relay config from your website. But I can  start "play" (button is disable)

How can debug or check how happens?

Thanks!
![Screenshot_2019-09-22 Dashboard FastoCloud](https://user-images.githubusercontent.com/18073752/65389416-625be580-dd2c-11e9-9cfe-44232740f469.png)

**Comment by topilski** [comment]
You need to activate according license_gen

**Comment by opaniagu** [comment]
Thanks!
