### ISSUE TITLE
End of File when try to play

### ISSUE THREAD

**Issue by opaniagu** [fastogt/fastocloud_admin#15]
Hi,

I try to play but receive "End of File". Attach server side.

Thanks

![Screenshot_2019-09-22 Dashboard FastoCloud(1)](https://user-images.githubusercontent.com/18073752/65389585-288bde80-dd2e-11e9-8ba1-4401658720cb.png)

**Comment by topilski** [comment]
Your input stream ended, a lot of restarts how you can see it is bad streams

**Comment by opaniagu** [comment]
can you give a guide how configure a relay?

**Comment by topilski** [comment]
First of all you need to check codecs in original stream and select according codecs parsers.
If it is hls simple insert http://ip:8080/master.m3u8 full url will be generated after save.

**Comment by opaniagu** [comment]
Excellent. Problem was audio codec.

Thanks
