### ISSUE TITLE
Source from ffmpeg or obsproject or wowza

### ISSUE THREAD

**Issue by opaniagu** [fastogt/fastocloud_admin#16]
Hi,

Can you add a wiki how integrate w/ ffmpeg or obsproject or wowza?

Thanks

**Comment by topilski** [comment]
Why do you need integrate ffmpeg?

**Comment by opaniagu** [comment]
Maybe a doc o wiki how use a ffmpeg or obsproject and nginx to stream and then how configure de relay inside fastcloud.

Thanks

**Comment by topilski** [comment]
Why we need ffmpeg if we have own media service?

**Comment by opaniagu** [comment]
I have two questions how to configure:
1) If I have a movie, for example: movie.mkv or movie.mp4, how can I stream it?
2) If I want to encode for example from the webcam? how configure it? And it is from local filesystem. Only if possible to define URL...not from local hard disk

Thanks

**Comment by topilski** [comment]
1) Create vod input file:///home/test/your.mp4 and output http://ip:8000/master.m3u8
2) You should insert webcams url and create encode type stream.

**Comment by opaniagu** [comment]
For 1) after confirmed button , http://ip:8000/master.m3u8 changed to 
http://localhost:7000/8/5d8b3732db8a5309e9e309fa/29314/master.m3u8
and when try to play server returned 404 Not Found

**Comment by opaniagu** [comment]
Sorry, but I can not found API to create VoD?
