### ISSUE TITLE
Video on Demand

### ISSUE THREAD

**Issue by opaniagu** [fastogt/fastocloud_admin#18]
Please, provide and example to configure the next file. 
 w/ http://www.html5videoplayer.net/videos/toystory.mp4
The idea is you download on local hard disk and then configure as VoD

Thanks in advanced

**Comment by topilski** [comment]
Simple setup this url in vods tab.

**Comment by opaniagu** [comment]
Server returned 404 Not Found....How can debug?

**Comment by topilski** [comment]
Also check logs

**Comment by opaniagu** [comment]
06:48:39.104 streamer_5d8b3732db8a5309e9e309fa [INFO] Successfully connected with client[[5d8b3732db8a5309e9e309fa][PipeClient(571)]], from server[[main][StreamServer(8)]], 1 client(s) connected.
../../../src/stream/streams_factory.cpp:132 06:48:39.105 streamer_5d8b3732db8a5309e9e309fa [CRITICAL] NOTREACHED() hit in CreateStream.

**Comment by topilski** [comment]
Can you create screenshoot of your stream settings?

**Comment by opaniagu** [comment]
![imagen](https://user-images.githubusercontent.com/18073752/65591360-c36cfe80-df62-11e9-8efa-9bead27c5fcf.png)

**Comment by topilski** [comment]
what is the protocol ///? file:///

**Comment by topilski** [comment]
also port for hls by default 8000

**Comment by opaniagu** [comment]
![imagen](https://user-images.githubusercontent.com/18073752/65591441-eb5c6200-df62-11e9-8cfc-e314c3464401.png)

**Comment by opaniagu** [comment]
Can you create and example on https://fastocloud.com please?

Thanks

**Comment by opaniagu** [comment]
Thanks!
