### ISSUE TITLE
How to start/use?

### ISSUE THREAD

**Issue by eisengrau** [fastogt/fastocloud_admin#3]
Hello,

Apparently I got this installed, including the IPTV server itself on the same machine. How do I start the service? On which ports does it run by default? From what URL should we access this?

Thank you,

**Comment by topilski** [comment]
./server.py but you need install mongodb and requirements

**Comment by eisengrau** [comment]
OK, got it now:

![image](https://user-images.githubusercontent.com/42865787/58637184-41d9cc80-82f2-11e9-97b9-28e06f42dfc1.png)

But, I need to register with a proper e-mail to log in, even if it's self-hosted? Isn't it possible to use it with a generic admin/admin account?

**Comment by topilski** [comment]
in script folder, please start create_user.py script

**Comment by eisengrau** [comment]
Nice! Much better, thank you. :)

I had to do mail instead of user:
`./create_user.py --mail=test@example.com`

It is possible to also get iptv_server made into a system service (which can be started up on boot)? Other than that, seems like all is ok, I'll try out some streams later on.

Thanks! :)

**Comment by topilski** [comment]
I'am not super gury of python script auto start but may be in future.

**Comment by topilski** [comment]
@eisengrau we created discord group for panel help: https://discord.gg/cnUXsws
