### ISSUE TITLE
ImportError: No module named 'gevent'

### ISSUE THREAD

**Issue by OLIMUTH** [fastogt/fastocloud_admin#34]
Traceback (most recent call last):
  File "./server.py", line 5, in <module>
    import gevent
ImportError: No module named 'gevent'

**Comment by topilski** [comment]
https://github.com/fastogt/fastocloud_admin/wiki/Build

**Comment by OLIMUTH** [comment]
I use this command pip3 install -r requirements.txt .it.shows this error



> Command "git clone -q git://github.com/fastogt/pyfastogt /tmp/pip-build-9bsb6pgu/pyfastogt" failed with error code 128 in None
You are using pip version 8.1.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
