### ISSUE TITLE
404 Client Error: Not Found for url: https://pypi.org/simple/pyfastogt/

### ISSUE THREAD

**Issue by kalashnikov2** [fastogt/fastocloud_admin#35]
unable to install due  404 error

requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/pyfastogt/

![imagen](https://user-images.githubusercontent.com/44566/88479622-22e6c280-cf16-11ea-9949-5e03612c66ec.png)

**Comment by topilski** [comment]
pip3 install -u pip

**Comment by kalashnikov2** [comment]
pip3 install -u pip 

Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: -u

**Comment by kalashnikov2** [comment]
so 

why the wiki home page do not have a link to 

https://github.com/fastogt/fastocloud_admin/wiki/Build   . . . . . 

![imagen](https://user-images.githubusercontent.com/44566/88479973-a43f5480-cf18-11ea-9405-4d651e5a2b33.png)
