### ISSUE TITLE
Pritect Streams

### ISSUE THREAD

**Issue by amjiddader** [fastogt/fastocloud_admin#39]
Hello,

Is there any way i can preven streams from public access.
example: my stream url is shared on forum and users can watch my streams .

i want to restrict streams to device , host, only.
so i can want stream on specific IP 
OR
i can watch stream on android app with specific package name i.e com.fastogt.iptv.

Regards

**Comment by topilski** [comment]
Hello, yes you can hide your stream via Android/iPhone app

**Comment by amjiddader** [comment]
Thanks, 
I already have my app. which works on a php backend.
in backend i add urls and that are played on app.
app is connected via API with server.

i want to restrict urls to be opned other than my app and i want this setting in fastocloud.

Regards

**Comment by topilski** [comment]
ok
