### ISSUE TITLE
Error when uploading m3u playlist

### ISSUE THREAD

**Issue by Juani1994** [fastogt/fastocloud_admin#40]
When trying to upload a m3u playlist from fastocloud admin, an error occurs: 
**Internal Server Error**
_The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application._

However, when i enter mongo database, the process of loading the playlist have been done. All channels from playslist are part of the db.

Another issue, is the Suscribers button on GUI. I can't change from false to true in app/config/config.py because the option "SUBSCRIBERS_SUPPORT" option isn't there; and if i add it manually, it doesn't work anyway

**Comment by topilski** [comment]
Fixed, subscribers not supported for this panel only in PRO version
