### ISSUE TITLE
Docker - creating new user

### ISSUE THREAD

**Issue by gear259** [fastogt/fastocloud_admin#7]
After command:-

Create user:
docker exec iptv_admin python3 /app/scripts/create_user.py --email=test@example.com --password=1234567 --mongo_uri=mongodb://mongodb:27017/iptv

-- issue = 'user not active'

**Comment by topilski** [comment]
I need to check, thank you

**Comment by topilski** [comment]
I can't reproduce, did mongodb image work?

**Comment by topilski** [comment]
Should be **fastocloud_admin** i think.

**Comment by topilski** [comment]
Here line which i used: `docker exec fastocloud_admin python3 /app/scripts/create_provider.py --email=test@example.com --password=1234567 --mongo_uri=mongodb://mongodb:27017/iptv`

**Comment by topilski** [comment]
Ping
